name: 刷步数15000-33333
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 17 7 * * *
  watch:
    types: started
 
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 开始
        run: |
          pip install requests
          pmode='pp'
          pkey='0a4c4a8fac2d4726b76a9a229788d460'
          user='13551175355#13281277984'
          pwd='13551175355HHwan#cp123456789'
          step='15000-33331'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
